# lightning.pytorch==2.4.0
seed_everything: 0
## Dataset
data:
  class_path: src.datasets.datamodules.DataModule
  init_args:
    dataset_type: acts_root
    dataset_dir: ../../actsODD/odd_output_tt_splits
    batch_size: 1024
    use_wrapper: True
    persistance: True
    kwargs:
      dataset_suffix: POC_eta_3_min_hits_7
      wrapper_workers: 0
      min_hits: 7
      min_pt: 0.5
      max_pt: 10
      keep_secondaries: False
      max_abs_eta: 3
      sort_by_radius: True
      cut_scattered: True
      truth_position: True
      input_variables:
        - tr
        - dphi
        - tz
      output_variables:
        - qopT
        - pz
